theme = "awesome-identity"
baseURL = "https://xander.naumenko.com"
title = "Xander Naumenko"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


## Profile Configurations
[params.profile]
  portrait = "profile-picture.jpg"
  firstname = "Xander"
  lastname = "Naumenko"
  title = "Software Dev and Quant Trader"
  bio = """An Engineering Physics student with a wide variety of experience in trading, software, firmware and electronics. 

Created a [**fully compliant RISC-V CPU inside Terraria**](https://youtu.be/zXPiqk0-zDY), made [**the avionics system for a rocket going to space**](https://github.com/UBC-Rocket/Whistler-Blackcomb-v2) and designed an [**autonomous foosball robot**](https://youtu.be/xrwXZXGiP1w), among other projects. 

  A self professed nerd who has spent altogether far too much time fiddling with Vim/Linux/<span class="latex">L<sup>a</sup>T<sub>e</sub>X</span> settings. 
  """

## Contacts Configurations
[params.contacts]
  email = "xander@naumenko.com"
  github = "misprit7"
  youtube = "built-from-scratch"
  linkedin = "xander-naumenko"

[params.actions.resume]
  name = "See my Resume"
  url = "./resume.pdf"

## Footer Configurations
[params.footer]
  poweredBy = false
