theme = "awesome-identity"
baseURL = "https://xander.naumenko.com"
title = "Xander Naumenko"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Xander"
  lastname = "Naumenko"
  title = "Software and Embedded Systems Developer"
  bio = """An Engineering Physics student with a wide variety of experience in software, firmware and electronics development. 

  Is the project lead for [**the avionics system for a rocket going to space**](https://github.com/UBC-Rocket/Whistler-Blackcomb-v2) and has designed a [**PCB business card**](https://github.com/misprit7/PCB-Business-Card), along with many other embedded systems projects. 

  Has 

  A self professed nerd who has spent altogether far to much time fiddling with vim/linux/<span class="latex">L<sup>A</sup>T<sub>E</sub>X</span></p> settings
  """

## Contacts Configurations
[params.contacts]
  email = "xandernaumenko@gmail.com"
  github = "misprit7"
  linkedin = "xander-naumenko"

[params.actions.resume]
  name = "See my Resume"
  url = "https://raw.githubusercontent.com/misprit7/resume/main/resume.pdf"

## Footer Configurations
[params.footer]
  poweredBy = true