theme = "awesome-identity"
baseURL = "https://xander.naumenko.com"
title = "Xander Naumenko"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


## Profile Configurations
[params.profile]
  portrait = "profile-picture.jpg"
  firstname = "Xander"
  lastname = "Naumenko"
  title = "Software and Embedded Systems Developer"
  bio = """An Engineering Physics student with a wide variety of experience in software, firmware and electronics development. 

  Is the project lead for [**the avionics system for a rocket going to space**](https://github.com/UBC-Rocket/Whistler-Blackcomb-v2), has designed a [**custom PCB business card**](https://github.com/misprit7/PCB-Business-Card) and has created [**chess database software**](https://github.com/misprit7/nacbko) from scratch, among other projects. 

  A self professed nerd who has spent altogether far to much time fiddling with Vim/Linux/<span class="latex">L<sup>a</sup>T<sub>e</sub>X</span> settings. 
  """

## Contacts Configurations
[params.contacts]
  email = "xander@naumenko.com"
  github = "misprit7"
  linkedin = "xander-naumenko"

[params.actions.resume]
  name = "See my Resume"
  url = "./resume.pdf"

## Footer Configurations
[params.footer]
  poweredBy = true
